[2025-04-08T18:50:36.635+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-08T18:50:36.670+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: init_elt_pipeline.load_data_from_minio_to_duckdb manual__2025-04-08T18:50:31.444899+00:00 [queued]>
[2025-04-08T18:50:36.678+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: init_elt_pipeline.load_data_from_minio_to_duckdb manual__2025-04-08T18:50:31.444899+00:00 [queued]>
[2025-04-08T18:50:36.678+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-04-08T18:50:36.691+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_data_from_minio_to_duckdb> on 2025-04-08 18:50:31.444899+00:00
[2025-04-08T18:50:36.698+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'init_elt_pipeline', 'load_data_from_minio_to_duckdb', 'manual__2025-04-08T18:50:31.444899+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/init_elt_pipeline.py', '--cfg-path', '/tmp/tmprs0vah3k']
[2025-04-08T18:50:36.698+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=387) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-08T18:50:36.699+0000] {standard_task_runner.py:91} INFO - Job 6: Subtask load_data_from_minio_to_duckdb
[2025-04-08T18:50:36.700+0000] {standard_task_runner.py:63} INFO - Started process 399 to run task
[2025-04-08T18:50:36.715+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-08T18:50:36.755+0000] {task_command.py:426} INFO - Running <TaskInstance: init_elt_pipeline.load_data_from_minio_to_duckdb manual__2025-04-08T18:50:31.444899+00:00 [running]> on host 0f264c2ad3d2
[2025-04-08T18:50:36.841+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='init_elt_pipeline' AIRFLOW_CTX_TASK_ID='load_data_from_minio_to_duckdb' AIRFLOW_CTX_EXECUTION_DATE='2025-04-08T18:50:31.444899+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-08T18:50:31.444899+00:00'
[2025-04-08T18:50:36.842+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-08T18:50:36.861+0000] {init_minio.py:24} INFO - Minio client connected successfully
[2025-04-08T18:50:36.889+0000] {extractor.py:137} ERROR - Error loading data to DuckDB: S3 operation failed; code: NoSuchKey, message: Object does not exist, resource: /bitcoin/temp/bitcoin-2021-01-01.csv, request_id: 18346C7C50DC546D, host_id: dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8, bucket_name: bitcoin, object_name: temp/bitcoin-2021-01-01.csv
[2025-04-08T18:50:36.889+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-04-08T18:50:36.891+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-08T18:50:36.935+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=init_elt_pipeline, task_id=load_data_from_minio_to_duckdb, run_id=manual__2025-04-08T18:50:31.444899+00:00, execution_date=20250408T185031, start_date=20250408T185036, end_date=20250408T185036
[2025-04-08T18:50:36.994+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-04-08T18:50:37.018+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-08T18:50:37.021+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
