[2025-04-08T19:06:34.702+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-08T19:06:34.736+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: init_elt_pipeline.upload_file_to_minio manual__2025-04-08T19:06:29.857603+00:00 [queued]>
[2025-04-08T19:06:34.743+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: init_elt_pipeline.upload_file_to_minio manual__2025-04-08T19:06:29.857603+00:00 [queued]>
[2025-04-08T19:06:34.744+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-04-08T19:06:34.760+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): upload_file_to_minio> on 2025-04-08 19:06:29.857603+00:00
[2025-04-08T19:06:34.769+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'init_elt_pipeline', 'upload_file_to_minio', 'manual__2025-04-08T19:06:29.857603+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/init_elt_pipeline.py', '--cfg-path', '/tmp/tmp4qxgfub4']
[2025-04-08T19:06:34.770+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=305) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-08T19:06:34.771+0000] {standard_task_runner.py:91} INFO - Job 4: Subtask upload_file_to_minio
[2025-04-08T19:06:34.771+0000] {standard_task_runner.py:63} INFO - Started process 317 to run task
[2025-04-08T19:06:34.788+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-08T19:06:34.825+0000] {task_command.py:426} INFO - Running <TaskInstance: init_elt_pipeline.upload_file_to_minio manual__2025-04-08T19:06:29.857603+00:00 [running]> on host 42f9042e0145
[2025-04-08T19:06:34.911+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='init_elt_pipeline' AIRFLOW_CTX_TASK_ID='upload_file_to_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-04-08T19:06:29.857603+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-08T19:06:29.857603+00:00'
[2025-04-08T19:06:34.912+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-08T19:06:34.930+0000] {init_minio.py:24} INFO - Minio client connected successfully
[2025-04-08T19:06:34.931+0000] {extractor.py:77} ERROR - Error uploading file to Minio: [Errno 2] No such file or directory: 'temp/bitcoin-2021-01-01.csv.csv'
[2025-04-08T19:06:34.932+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-04-08T19:06:34.934+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-08T19:06:34.944+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=init_elt_pipeline, task_id=upload_file_to_minio, run_id=manual__2025-04-08T19:06:29.857603+00:00, execution_date=20250408T190629, start_date=20250408T190634, end_date=20250408T190634
[2025-04-08T19:06:34.986+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-04-08T19:06:35.032+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-08T19:06:35.036+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
