[2025-04-05T10:45:12.594+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-05T10:45:12.634+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt_pipeline.get_coin_data scheduled__2025-04-04T00:00:00+00:00 [queued]>
[2025-04-05T10:45:12.642+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt_pipeline.get_coin_data scheduled__2025-04-04T00:00:00+00:00 [queued]>
[2025-04-05T10:45:12.644+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-04-05T10:45:12.662+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_coin_data> on 2025-04-04 00:00:00+00:00
[2025-04-05T10:45:12.671+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'elt_pipeline', 'get_coin_data', 'scheduled__2025-04-04T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/elt_pipeline.py', '--cfg-path', '/tmp/tmp88xdgvuc']
[2025-04-05T10:45:12.671+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=237) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-05T10:45:12.672+0000] {standard_task_runner.py:91} INFO - Job 2: Subtask get_coin_data
[2025-04-05T10:45:12.673+0000] {standard_task_runner.py:63} INFO - Started process 260 to run task
[2025-04-05T10:45:12.694+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-05T10:45:12.748+0000] {task_command.py:426} INFO - Running <TaskInstance: elt_pipeline.get_coin_data scheduled__2025-04-04T00:00:00+00:00 [running]> on host d56545bf874e
[2025-04-05T10:45:12.864+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt_pipeline' AIRFLOW_CTX_TASK_ID='get_coin_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-04T00:00:00+00:00'
[2025-04-05T10:45:12.865+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-05T10:45:13.079+0000] {logging_mixin.py:188} INFO - Error fetching data: 429 Client Error: Too Many Requests for url: https://api.coincap.io/v2/assets/bitcoin/history?interval=h1&start=1609459200000&end=1609545599999
[2025-04-05T10:45:13.081+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-04-05T10:45:13.082+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-05T10:45:13.095+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=elt_pipeline, task_id=get_coin_data, run_id=scheduled__2025-04-04T00:00:00+00:00, execution_date=20250404T000000, start_date=20250405T104512, end_date=20250405T104513
[2025-04-05T10:45:13.132+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-04-05T10:45:13.165+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-05T10:45:13.169+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-04-05T11:10:22.689+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-05T11:10:22.725+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt_pipeline.get_coin_data scheduled__2025-04-04T00:00:00+00:00 [queued]>
[2025-04-05T11:10:22.732+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt_pipeline.get_coin_data scheduled__2025-04-04T00:00:00+00:00 [queued]>
[2025-04-05T11:10:22.732+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-04-05T11:10:22.748+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_coin_data> on 2025-04-04 00:00:00+00:00
[2025-04-05T11:10:22.757+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=305) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-05T11:10:22.757+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'elt_pipeline', 'get_coin_data', 'scheduled__2025-04-04T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/elt_pipeline.py', '--cfg-path', '/tmp/tmpydr4apff']
[2025-04-05T11:10:22.758+0000] {standard_task_runner.py:63} INFO - Started process 329 to run task
[2025-04-05T11:10:22.759+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask get_coin_data
[2025-04-05T11:10:22.777+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-05T11:10:22.824+0000] {task_command.py:426} INFO - Running <TaskInstance: elt_pipeline.get_coin_data scheduled__2025-04-04T00:00:00+00:00 [running]> on host 1b61a216da47
[2025-04-05T11:10:22.947+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt_pipeline' AIRFLOW_CTX_TASK_ID='get_coin_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-04T00:00:00+00:00'
[2025-04-05T11:10:22.949+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-05T11:10:23.141+0000] {logging_mixin.py:188} INFO - Error fetching data: 429 Client Error: Too Many Requests for url: https://api.coincap.io/v2/assets/bitcoin/history?interval=h1&start=1609459200000&end=1609545599999
[2025-04-05T11:10:23.142+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-04-05T11:10:23.144+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-05T11:10:23.162+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=elt_pipeline, task_id=get_coin_data, run_id=scheduled__2025-04-04T00:00:00+00:00, execution_date=20250404T000000, start_date=20250405T111022, end_date=20250405T111023
[2025-04-05T11:10:23.218+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-04-05T11:10:23.262+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-05T11:10:23.266+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-04-05T15:55:33.693+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-05T15:55:33.730+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt_pipeline.get_coin_data scheduled__2025-04-04T00:00:00+00:00 [queued]>
[2025-04-05T15:55:33.740+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt_pipeline.get_coin_data scheduled__2025-04-04T00:00:00+00:00 [queued]>
[2025-04-05T15:55:33.741+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-04-05T15:55:33.754+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_coin_data> on 2025-04-04 00:00:00+00:00
[2025-04-05T15:55:33.763+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=485) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-05T15:55:33.763+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'elt_pipeline', 'get_coin_data', 'scheduled__2025-04-04T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/elt_pipeline.py', '--cfg-path', '/tmp/tmpjwfql8t4']
[2025-04-05T15:55:33.765+0000] {standard_task_runner.py:63} INFO - Started process 508 to run task
[2025-04-05T15:55:33.765+0000] {standard_task_runner.py:91} INFO - Job 2: Subtask get_coin_data
[2025-04-05T15:55:33.787+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-05T15:55:33.844+0000] {task_command.py:426} INFO - Running <TaskInstance: elt_pipeline.get_coin_data scheduled__2025-04-04T00:00:00+00:00 [running]> on host a4017603cc0b
[2025-04-05T15:55:33.994+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt_pipeline' AIRFLOW_CTX_TASK_ID='get_coin_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-04T00:00:00+00:00'
[2025-04-05T15:55:33.995+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-05T15:55:34.228+0000] {logging_mixin.py:188} INFO - Error fetching data: 429 Client Error: Too Many Requests for url: https://api.coincap.io/v2/assets/bitcoin/history?interval=h1&start=1609459200000&end=1609545599999
[2025-04-05T15:55:34.230+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-04-05T15:55:34.232+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-05T15:55:34.248+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=elt_pipeline, task_id=get_coin_data, run_id=scheduled__2025-04-04T00:00:00+00:00, execution_date=20250404T000000, start_date=20250405T155533, end_date=20250405T155534
[2025-04-05T15:55:34.304+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-04-05T15:55:34.342+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-05T15:55:34.344+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-04-05T16:31:53.062+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-05T16:31:53.095+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt_pipeline.get_coin_data scheduled__2025-04-04T00:00:00+00:00 [queued]>
[2025-04-05T16:31:53.102+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt_pipeline.get_coin_data scheduled__2025-04-04T00:00:00+00:00 [queued]>
[2025-04-05T16:31:53.103+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-04-05T16:31:53.116+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_coin_data> on 2025-04-04 00:00:00+00:00
[2025-04-05T16:31:53.125+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=240) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-05T16:31:53.125+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'elt_pipeline', 'get_coin_data', 'scheduled__2025-04-04T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/elt_pipeline.py', '--cfg-path', '/tmp/tmp_p4plxsx']
[2025-04-05T16:31:53.126+0000] {standard_task_runner.py:63} INFO - Started process 264 to run task
[2025-04-05T16:31:53.127+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask get_coin_data
[2025-04-05T16:31:53.143+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-05T16:31:53.185+0000] {task_command.py:426} INFO - Running <TaskInstance: elt_pipeline.get_coin_data scheduled__2025-04-04T00:00:00+00:00 [running]> on host d060e19f414c
[2025-04-05T16:31:53.278+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt_pipeline' AIRFLOW_CTX_TASK_ID='get_coin_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-04T00:00:00+00:00'
[2025-04-05T16:31:53.280+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-05T16:31:53.470+0000] {logging_mixin.py:188} INFO - Error fetching data: 429 Client Error: Too Many Requests for url: https://api.coincap.io/v2/assets/bitcoin/history?interval=h1&start=1609459200000&end=1609545599999
[2025-04-05T16:31:53.472+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-04-05T16:31:53.474+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-05T16:31:53.488+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=elt_pipeline, task_id=get_coin_data, run_id=scheduled__2025-04-04T00:00:00+00:00, execution_date=20250404T000000, start_date=20250405T163153, end_date=20250405T163153
[2025-04-05T16:31:53.547+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-04-05T16:31:53.579+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-05T16:31:53.582+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-04-05T16:41:13.262+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-05T16:41:13.298+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt_pipeline.get_coin_data scheduled__2025-04-04T00:00:00+00:00 [queued]>
[2025-04-05T16:41:13.307+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt_pipeline.get_coin_data scheduled__2025-04-04T00:00:00+00:00 [queued]>
[2025-04-05T16:41:13.307+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-04-05T16:41:13.326+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_coin_data> on 2025-04-04 00:00:00+00:00
[2025-04-05T16:41:13.333+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'elt_pipeline', 'get_coin_data', 'scheduled__2025-04-04T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/elt_pipeline.py', '--cfg-path', '/tmp/tmp9c_2dffu']
[2025-04-05T16:41:13.333+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=239) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-05T16:41:13.334+0000] {standard_task_runner.py:91} INFO - Job 2: Subtask get_coin_data
[2025-04-05T16:41:13.335+0000] {standard_task_runner.py:63} INFO - Started process 251 to run task
[2025-04-05T16:41:13.355+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-05T16:41:13.398+0000] {task_command.py:426} INFO - Running <TaskInstance: elt_pipeline.get_coin_data scheduled__2025-04-04T00:00:00+00:00 [running]> on host 658edd075563
[2025-04-05T16:41:13.509+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt_pipeline' AIRFLOW_CTX_TASK_ID='get_coin_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-04T00:00:00+00:00'
[2025-04-05T16:41:13.511+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-05T16:41:13.693+0000] {logging_mixin.py:188} INFO - Error fetching data: 429 Client Error: Too Many Requests for url: https://api.coincap.io/v2/assets/bitcoin/history?interval=h1&start=1609459200000&end=1609545599999
[2025-04-05T16:41:13.695+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-04-05T16:41:13.697+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-05T16:41:13.708+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=elt_pipeline, task_id=get_coin_data, run_id=scheduled__2025-04-04T00:00:00+00:00, execution_date=20250404T000000, start_date=20250405T164113, end_date=20250405T164113
[2025-04-05T16:41:13.765+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-04-05T16:41:13.791+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-05T16:41:13.795+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-04-05T16:43:41.754+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-05T16:43:41.790+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt_pipeline.get_coin_data scheduled__2025-04-04T00:00:00+00:00 [queued]>
[2025-04-05T16:43:41.797+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt_pipeline.get_coin_data scheduled__2025-04-04T00:00:00+00:00 [queued]>
[2025-04-05T16:43:41.797+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-04-05T16:43:41.814+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_coin_data> on 2025-04-04 00:00:00+00:00
[2025-04-05T16:43:41.823+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'elt_pipeline', 'get_coin_data', 'scheduled__2025-04-04T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/elt_pipeline.py', '--cfg-path', '/tmp/tmp_2uo9p6t']
[2025-04-05T16:43:41.823+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=239) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-05T16:43:41.825+0000] {standard_task_runner.py:91} INFO - Job 2: Subtask get_coin_data
[2025-04-05T16:43:41.825+0000] {standard_task_runner.py:63} INFO - Started process 251 to run task
[2025-04-05T16:43:41.846+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-05T16:43:41.888+0000] {task_command.py:426} INFO - Running <TaskInstance: elt_pipeline.get_coin_data scheduled__2025-04-04T00:00:00+00:00 [running]> on host 1f8025531576
[2025-04-05T16:43:41.988+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt_pipeline' AIRFLOW_CTX_TASK_ID='get_coin_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-04T00:00:00+00:00'
[2025-04-05T16:43:41.989+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-05T16:43:42.168+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-04-05T16:43:42.169+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-05T16:43:42.180+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=elt_pipeline, task_id=get_coin_data, run_id=scheduled__2025-04-04T00:00:00+00:00, execution_date=20250404T000000, start_date=20250405T164341, end_date=20250405T164342
[2025-04-05T16:43:42.210+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-04-05T16:43:42.237+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-05T16:43:42.241+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-04-05T17:21:47.940+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-05T17:21:47.979+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt_pipeline.get_coin_data scheduled__2025-04-04T00:00:00+00:00 [queued]>
[2025-04-05T17:21:47.987+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt_pipeline.get_coin_data scheduled__2025-04-04T00:00:00+00:00 [queued]>
[2025-04-05T17:21:47.988+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-04-05T17:21:48.002+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_coin_data> on 2025-04-04 00:00:00+00:00
[2025-04-05T17:21:48.009+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=282) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-05T17:21:48.009+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'elt_pipeline', 'get_coin_data', 'scheduled__2025-04-04T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/elt_pipeline.py', '--cfg-path', '/tmp/tmpbpq8adzf']
[2025-04-05T17:21:48.010+0000] {standard_task_runner.py:63} INFO - Started process 294 to run task
[2025-04-05T17:21:48.011+0000] {standard_task_runner.py:91} INFO - Job 2: Subtask get_coin_data
[2025-04-05T17:21:48.027+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-05T17:21:48.066+0000] {task_command.py:426} INFO - Running <TaskInstance: elt_pipeline.get_coin_data scheduled__2025-04-04T00:00:00+00:00 [running]> on host 3662cb577b20
[2025-04-05T17:21:48.154+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt_pipeline' AIRFLOW_CTX_TASK_ID='get_coin_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-04T00:00:00+00:00'
[2025-04-05T17:21:48.155+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-05T17:21:48.452+0000] {logging_mixin.py:188} INFO - Error fetching data: 429 Client Error: Too Many Requests for url: https://api.coincap.io/v2/assets/bitcoin/history?interval=h1&start=1609459200000&end=1609545599999
[2025-04-05T17:21:48.454+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-04-05T17:21:48.456+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-05T17:21:48.468+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=elt_pipeline, task_id=get_coin_data, run_id=scheduled__2025-04-04T00:00:00+00:00, execution_date=20250404T000000, start_date=20250405T172147, end_date=20250405T172148
[2025-04-05T17:21:48.514+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-04-05T17:21:48.537+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-05T17:21:48.540+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-04-05T17:29:05.943+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-05T17:29:05.975+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt_pipeline.get_coin_data scheduled__2025-04-04T00:00:00+00:00 [queued]>
[2025-04-05T17:29:05.981+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt_pipeline.get_coin_data scheduled__2025-04-04T00:00:00+00:00 [queued]>
[2025-04-05T17:29:05.982+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-04-05T17:29:05.994+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_coin_data> on 2025-04-04 00:00:00+00:00
[2025-04-05T17:29:06.001+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=281) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-05T17:29:06.001+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'elt_pipeline', 'get_coin_data', 'scheduled__2025-04-04T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/elt_pipeline.py', '--cfg-path', '/tmp/tmp5d04jg4j']
[2025-04-05T17:29:06.002+0000] {standard_task_runner.py:63} INFO - Started process 293 to run task
[2025-04-05T17:29:06.002+0000] {standard_task_runner.py:91} INFO - Job 2: Subtask get_coin_data
[2025-04-05T17:29:06.019+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-05T17:29:06.057+0000] {task_command.py:426} INFO - Running <TaskInstance: elt_pipeline.get_coin_data scheduled__2025-04-04T00:00:00+00:00 [running]> on host de3d8b486e6c
[2025-04-05T17:29:06.154+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt_pipeline' AIRFLOW_CTX_TASK_ID='get_coin_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-04T00:00:00+00:00'
[2025-04-05T17:29:06.156+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-05T17:29:06.342+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-04-05T17:29:06.343+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-05T17:29:06.354+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=elt_pipeline, task_id=get_coin_data, run_id=scheduled__2025-04-04T00:00:00+00:00, execution_date=20250404T000000, start_date=20250405T172905, end_date=20250405T172906
[2025-04-05T17:29:06.387+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-04-05T17:29:06.399+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
