[2025-04-09T08:27:14.552+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-09T08:27:14.583+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: elt_pipeline.upload_file_to_minio scheduled__2025-04-08T00:00:00+00:00 [queued]>
[2025-04-09T08:27:14.590+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: elt_pipeline.upload_file_to_minio scheduled__2025-04-08T00:00:00+00:00 [queued]>
[2025-04-09T08:27:14.592+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-04-09T08:27:14.606+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): upload_file_to_minio> on 2025-04-08 00:00:00+00:00
[2025-04-09T08:27:14.613+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=889) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-09T08:27:14.614+0000] {standard_task_runner.py:63} INFO - Started process 901 to run task
[2025-04-09T08:27:14.613+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'elt_pipeline', 'upload_file_to_minio', 'scheduled__2025-04-08T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/elt_pipeline.py', '--cfg-path', '/tmp/tmp_ylz1a5r']
[2025-04-09T08:27:14.615+0000] {standard_task_runner.py:91} INFO - Job 9: Subtask upload_file_to_minio
[2025-04-09T08:27:14.633+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-09T08:27:14.674+0000] {task_command.py:426} INFO - Running <TaskInstance: elt_pipeline.upload_file_to_minio scheduled__2025-04-08T00:00:00+00:00 [running]> on host 208e59669cb5
[2025-04-09T08:27:14.759+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='elt_pipeline' AIRFLOW_CTX_TASK_ID='upload_file_to_minio' AIRFLOW_CTX_EXECUTION_DATE='2025-04-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-08T00:00:00+00:00'
[2025-04-09T08:27:14.760+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-09T08:27:15.361+0000] {extractor.py:97} INFO - Last load date: 2021-01-03
[2025-04-09T08:27:15.362+0000] {extractor.py:98} INFO - Next load date: 2021-01-04
[2025-04-09T08:27:15.371+0000] {init_minio.py:24} INFO - Minio client connected successfully
[2025-04-09T08:27:15.372+0000] {extractor.py:77} ERROR - Error uploading file to Minio: [Errno 2] No such file or directory: 'temp/bitcoin-2021-01-04.csv'
[2025-04-09T08:27:15.372+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-04-09T08:27:15.373+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-09T08:27:15.385+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=elt_pipeline, task_id=upload_file_to_minio, run_id=scheduled__2025-04-08T00:00:00+00:00, execution_date=20250408T000000, start_date=20250409T082714, end_date=20250409T082715
[2025-04-09T08:27:15.471+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-04-09T08:27:15.491+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-09T08:27:15.496+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
